name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          docker build -t johnahn/docker-react-app -f Dockerfile.dev .
          docker run -e CI=true johnahn/docker-react-app npm run test -- --coverage